/* 
 * CDR API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.CDR.Client;
using Cloudmersive.APIClient.NET.CDR.Api;

namespace Cloudmersive.APIClient.NET.CDR.Test
{
    /// <summary>
    ///  Class for testing FileSanitizationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FileSanitizationApiTests
    {
        private FileSanitizationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FileSanitizationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileSanitizationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FileSanitizationApi
            //Assert.IsInstanceOfType(typeof(FileSanitizationApi), instance, "instance is a FileSanitizationApi");
        }

        
        /// <summary>
        /// Test File
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //instance.File(inputFile);
            
        }
        
        /// <summary>
        /// Test FileToPdf
        /// </summary>
        [Test]
        public void FileToPdfTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //instance.FileToPdf(inputFile);
            
        }
        
    }

}
