/* 
 * CDR API
 *
 * Use the Content Disarm and Reconstruction API to remove security risks from documents by tearing them down, removing unsafe content and rebuilding them.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.CDR.Client;
using Cloudmersive.APIClient.NET.CDR.Api;
using Cloudmersive.APIClient.NET.CDR.Model;

namespace Cloudmersive.APIClient.NET.CDR.Test
{
    /// <summary>
    ///  Class for testing FileSanitizationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FileSanitizationApiTests
    {
        private FileSanitizationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FileSanitizationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileSanitizationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FileSanitizationApi
            //Assert.IsInstanceOfType(typeof(FileSanitizationApi), instance, "instance is a FileSanitizationApi");
        }

        
        /// <summary>
        /// Test CallFile
        /// </summary>
        [Test]
        public void CallFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //var response = instance.CallFile(inputFile);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test FileAdvanced
        /// </summary>
        [Test]
        public void FileAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? allowExecutables = null;
            //bool? allowInvalidFiles = null;
            //bool? allowScripts = null;
            //bool? allowPasswordProtectedFiles = null;
            //bool? allowMacros = null;
            //bool? allowXmlExternalEntities = null;
            //bool? allowInsecureDeserialization = null;
            //bool? allowHtml = null;
            //bool? allowUnsafeArchives = null;
            //bool? allowOleEmbeddedObject = null;
            //bool? allowUnwantedAction = null;
            //string restrictFileTypes = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.FileAdvanced(allowExecutables, allowInvalidFiles, allowScripts, allowPasswordProtectedFiles, allowMacros, allowXmlExternalEntities, allowInsecureDeserialization, allowHtml, allowUnsafeArchives, allowOleEmbeddedObject, allowUnwantedAction, restrictFileTypes, inputFile);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test FileToPdf
        /// </summary>
        [Test]
        public void FileToPdfTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream inputFile = null;
            //var response = instance.FileToPdf(inputFile);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test FileToPdfAdvanced
        /// </summary>
        [Test]
        public void FileToPdfAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? allowExecutables = null;
            //bool? allowInvalidFiles = null;
            //bool? allowScripts = null;
            //bool? allowPasswordProtectedFiles = null;
            //bool? allowMacros = null;
            //bool? allowXmlExternalEntities = null;
            //bool? allowInsecureDeserialization = null;
            //bool? allowHtml = null;
            //bool? allowUnsafeArchives = null;
            //bool? allowOleEmbeddedObject = null;
            //bool? allowUnwantedAction = null;
            //string restrictFileTypes = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.FileToPdfAdvanced(allowExecutables, allowInvalidFiles, allowScripts, allowPasswordProtectedFiles, allowMacros, allowXmlExternalEntities, allowInsecureDeserialization, allowHtml, allowUnsafeArchives, allowOleEmbeddedObject, allowUnwantedAction, restrictFileTypes, inputFile);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
    }

}
